schema_version: 1

context:
  version: "0.2.2"

package:
  name: refleak
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/refleak/refleak-${{ version }}.tar.gz
  sha256: c9cfd5054e1703edf4489fb0418aee930cb6f0eeb4f64fb81a6a64772d1841c2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - refleak
      pip_check: true

about:
  summary: Find out what's still holding a reference to an object that should be dead.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/mne-tools/refleak

extra:
  recipe-maintainers:
    - larsoner
